name: Build kernel
on:
  push:
    branches:
      - debian/master
      - 'wip/**'

jobs:
  build_kernel:
    name: Build kernel
    runs-on: ubuntu-latest
    container:
      image: debian:bookworm
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo "deb http://deb.debian.org/debian bookworm main" > /etc/apt/sources.list
          echo "deb-src http://deb.debian.org/debian bookworm main" >> /etc/apt/sources.list
          apt-get update
          apt-get --yes build-dep linux
          apt-get --yes install devscripts \
                                fakeroot

      - name: Build image
        run: |
          make ARCH=x86 resctl-demo_defconfig
          make ARCH=x86 -j$(nproc) bindeb-pkg
          mkdir out && dcmd mv ../*.changes out/

      - name: Publish artifacts
        uses: actions/upload-artifact@v2
        with:
          name: resctl-demo-kernel
          path: out/
          if-no-files-found: error

